/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author G
 */
public class Przeliczanie extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Przeliczanie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ko_jPanel = new javax.swing.JPanel();
        ko_jLabelPrzeliczanieJed = new javax.swing.JLabel();
        ko_jLabelOdl = new javax.swing.JLabel();
        ko_jButtonPrzelicz1 = new javax.swing.JButton();
        ko_jLabelTemperature = new javax.swing.JLabel();
        ko_jButtonPrzelicz2 = new javax.swing.JButton();
        ko_jLabelWO = new javax.swing.JLabel();
        ko_jSpinnerOdl = new javax.swing.JSpinner();
        ko_jRadioButtonKil = new javax.swing.JRadioButton();
        ko_jRadioButtonMetry = new javax.swing.JRadioButton();
        ko_jRadioButtonCale = new javax.swing.JRadioButton();
        ko_jLabelWpt = new javax.swing.JLabel();
        ko_jSpinnerTem = new javax.swing.JSpinner();
        ko_jRadioButtonC = new javax.swing.JRadioButton();
        ko_jRadioButtonK = new javax.swing.JRadioButton();
        ko_jRadioButtonF = new javax.swing.JRadioButton();
        ko_jMenuBar = new javax.swing.JMenuBar();
        ko_jMenuPlik = new javax.swing.JMenu();
        ko_jMenuItemPokażHis = new javax.swing.JMenuItem();
        ko_jMenuItemZapisz = new javax.swing.JMenuItem();
        ko_jMenuOProgramie = new javax.swing.JMenu();
        ko_jMenuItemO = new javax.swing.JMenuItem();
        ko_jMenuZamknij = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ko_jPanel.setBackground(new java.awt.Color(204, 255, 204));

        ko_jLabelPrzeliczanieJed.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        ko_jLabelPrzeliczanieJed.setText("Przeliczanie Jednostek");

        ko_jLabelOdl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_jLabelOdl.setText("Przelicz Odległość");

        ko_jButtonPrzelicz1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_jButtonPrzelicz1.setText("PRZELICZ");

        ko_jLabelTemperature.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_jLabelTemperature.setText("Przelicz Temperaturę");

        ko_jButtonPrzelicz2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_jButtonPrzelicz2.setText("PRZELICZ");

        ko_jLabelWO.setText("Wprowadz Odległość");

        ko_jRadioButtonKil.setText("Kilometry");

        ko_jRadioButtonMetry.setText("Metry");

        ko_jRadioButtonCale.setText("Cale");

        ko_jLabelWpt.setText("Wprowadz Temperaturę");

        ko_jRadioButtonC.setText("C");

        ko_jRadioButtonK.setText("K");

        ko_jRadioButtonF.setText("F");

        javax.swing.GroupLayout ko_jPanelLayout = new javax.swing.GroupLayout(ko_jPanel);
        ko_jPanel.setLayout(ko_jPanelLayout);
        ko_jPanelLayout.setHorizontalGroup(
            ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ko_jRadioButtonMetry, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(ko_jRadioButtonCale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 620, Short.MAX_VALUE))
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ko_jLabelOdl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_jLabelWO)
                            .addComponent(ko_jSpinnerOdl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_jRadioButtonKil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ko_jPanelLayout.createSequentialGroup()
                                .addComponent(ko_jLabelWpt)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ko_jPanelLayout.createSequentialGroup()
                                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ko_jLabelTemperature)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ko_jPanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ko_jRadioButtonF)
                                            .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ko_jRadioButtonK)
                                                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ko_jRadioButtonC)
                                                    .addComponent(ko_jSpinnerTem))))))
                                .addGap(44, 44, 44))))))
            .addGroup(ko_jPanelLayout.createSequentialGroup()
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(ko_jLabelPrzeliczanieJed, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ko_jButtonPrzelicz1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ko_jButtonPrzelicz2)))
                .addContainerGap())
        );
        ko_jPanelLayout.setVerticalGroup(
            ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelLayout.createSequentialGroup()
                .addComponent(ko_jLabelPrzeliczanieJed, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelOdl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jLabelTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelWO)
                    .addComponent(ko_jLabelWpt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jSpinnerOdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jSpinnerTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jRadioButtonKil)
                    .addComponent(ko_jRadioButtonC))
                .addGap(12, 12, 12)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jRadioButtonMetry)
                    .addComponent(ko_jRadioButtonK))
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ko_jRadioButtonCale))
                    .addGroup(ko_jPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ko_jRadioButtonF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(ko_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jButtonPrzelicz1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jButtonPrzelicz2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ko_jMenuPlik.setText("Plik");

        ko_jMenuItemPokażHis.setText("Pokaż Historię");
        ko_jMenuPlik.add(ko_jMenuItemPokażHis);

        ko_jMenuItemZapisz.setText("Zapisz Działanie(KLIKNIJ)");
        ko_jMenuPlik.add(ko_jMenuItemZapisz);

        ko_jMenuBar.add(ko_jMenuPlik);

        ko_jMenuOProgramie.setText("O Programie");

        ko_jMenuItemO.setText("O Programie(KLIKNIJ)");
        ko_jMenuOProgramie.add(ko_jMenuItemO);

        ko_jMenuBar.add(ko_jMenuOProgramie);

        ko_jMenuZamknij.setText("Zamknij Program");

        jMenuItem1.setText("ZAMKNIJ(KLIKNIJ)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ko_jMenuZamknij.add(jMenuItem1);

        ko_jMenuBar.add(ko_jMenuZamknij);

        setJMenuBar(ko_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ko_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ko_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przeliczanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton ko_jButtonPrzelicz1;
    private javax.swing.JButton ko_jButtonPrzelicz2;
    private javax.swing.JLabel ko_jLabelOdl;
    private javax.swing.JLabel ko_jLabelPrzeliczanieJed;
    private javax.swing.JLabel ko_jLabelTemperature;
    private javax.swing.JLabel ko_jLabelWO;
    private javax.swing.JLabel ko_jLabelWpt;
    private javax.swing.JMenuBar ko_jMenuBar;
    private javax.swing.JMenuItem ko_jMenuItemO;
    private javax.swing.JMenuItem ko_jMenuItemPokażHis;
    private javax.swing.JMenuItem ko_jMenuItemZapisz;
    private javax.swing.JMenu ko_jMenuOProgramie;
    private javax.swing.JMenu ko_jMenuPlik;
    private javax.swing.JMenu ko_jMenuZamknij;
    private javax.swing.JPanel ko_jPanel;
    private javax.swing.JRadioButton ko_jRadioButtonC;
    private javax.swing.JRadioButton ko_jRadioButtonCale;
    private javax.swing.JRadioButton ko_jRadioButtonF;
    private javax.swing.JRadioButton ko_jRadioButtonK;
    private javax.swing.JRadioButton ko_jRadioButtonKil;
    private javax.swing.JRadioButton ko_jRadioButtonMetry;
    private javax.swing.JSpinner ko_jSpinnerOdl;
    private javax.swing.JSpinner ko_jSpinnerTem;
    // End of variables declaration//GEN-END:variables
}
